:: don't close automatically
if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )

:::::::::::::: BCV and BCV-CoT :::::::::::::::::

:: MEDQUAD, MEDICAL, COT
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/medquad_medical_cot_llama3.json --logfile logs/medquad_medical_cot_llama3.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/medquad_medical_cot_llama3-gradient.json --logfile logs/medquad_medical_cot_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/medquad_medical_cot_nous-hermes2.json --logfile logs/medquad_medical_cot_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/medquad_medical_cot_gemma.json --logfile logs/medquad_medical_cot_gemma.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/medquad_medical_cot_mistral.json --logfile logs/medquad_medical_cot_mistral.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/medquad_medical_cot_llama2.json --logfile logs/medquad_medical_cot_llama2.log

:: MEDQUAD, AGNOSTIC, COT
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/medquad_agnostic_cot_llama3.json --logfile logs/medquad_agnostic_cot_llama3.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/medquad_agnostic_cot_nous-hermes2.json --logfile logs/medquad_agnostic_cot_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/medquad_agnostic_cot_gemma.json --logfile logs/medquad_agnostic_cot_gemma.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/medquad_agnostic_cot_mistral.json --logfile logs/medquad_agnostic_cot_mistral.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/medquad_agnostic_cot_llama2.json --logfile logs/medquad_agnostic_cot_llama2.log

:: MEDQUAD, MEDICAL, NOCOT
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/medquad_medical_llama3.json --logfile logs/medquad_medical_llama3.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/medquad_medical_llama3-gradient.json --logfile logs/medquad_medical_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/medquad_medical_nous-hermes2.json --logfile logs/medquad_medical_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/medquad_medical_gemma.json --logfile logs/medquad_medical_gemma.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/medquad_medical_mistral.json --logfile logs/medquad_medical_mistral.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/medquad_medical_llama2.json --logfile logs/medquad_medical_llama2.log

:: MEDQUAD, AGNOSTIC, NOCOT
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/medquad_agnostic_llama3.json --logfile logs/medquad_agnostic_llama3.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/medquad_agnostic_llama3-gradient.json --logfile logs/medquad_agnostic_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/medquad_agnostic_nous-hermes2.json --logfile logs/medquad_agnostic_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/medquad_agnostic_gemma.json --logfile logs/medquad_agnostic_gemma.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/medquad_agnostic_mistral.json --logfile logs/medquad_agnostic_mistral.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/medquad_agnostic_llama2-13b.json --logfile logs/medquad_agnostic_llama2-13b.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/medquad_agnostic_llama2.json --logfile logs/medquad_agnostic_llama2.log

:: HALUEVAL, AGNOSTIC, NOCOT
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/halueval_agnostic_nocot_llama3.json --logfile logs/halueval_agnostic_nocot_llama3.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/halueval_agnostic_nocot_llama3-gradient.json --logfile logs/halueval_agnostic_nocot_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/halueval_agnostic_nocot_nous-hermes2.json --logfile logs/halueval_agnostic_nocot_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/halueval_agnostic_nocot_gemma.json --logfile logs/halueval_agnostic_nocot_gemma.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/halueval_agnostic_nocot_mistral.json --logfile logs/halueval_agnostic_nocot_mistral.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/halueval_agnostic_nocot_llama2.json --logfile logs/halueval_agnostic_nocot_llama2.log

:: HALUEVAL, AGNOSTIC, COT
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/halueval_agnostic_cot_llama3.json --logfile logs/halueval_agnostic_cot_llama3.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/halueval_agnostic_cot_llama3-gradient.json --logfile logs/halueval_agnostic_cot_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/halueval_agnostic_cot_nous-hermes2.json --logfile logs/halueval_agnostic_cot_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/halueval_agnostic_cot_gemma.json --logfile logs/halueval_agnostic_cot_gemma.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/halueval_agnostic_cot_mistral.json --logfile logs/halueval_agnostic_cot_mistral.log
::py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/halueval_agnostic_cot_llama2.json --logfile logs/halueval_agnostic_cot_llama2.log

:: EHR, AGNOSTIC, NOCOT
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/ehr_agnostic_nocot_llama3.json --logfile logs/ehr_agnostic_nocot_llama3.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/ehr_agnostic_nocot_llama3-gradient.json --logfile logs/ehr_agnostic_nocot_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/ehr_agnostic_nocot_nous-hermes2.json --logfile logs/ehr_agnostic_nocot_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/ehr_agnostic_nocot_gemma.json --logfile logs/ehr_agnostic_nocot_gemma.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/ehr_agnostic_nocot_mistral.json --logfile logs/ehr_agnostic_nocot_mistral.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/ehr_agnostic_nocot_llama2.json --logfile logs/ehr_agnostic_nocot_llama2.log

:: EHR, AGNOSTIC, COT
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/ehr_agnostic_cot_llama3.json --logfile logs/ehr_agnostic_cot_llama3.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/ehr_agnostic_cot_nous-hermes2.json --logfile logs/ehr_agnostic_cot_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/ehr_agnostic_cot_gemma.json --logfile logs/ehr_agnostic_cot_gemma.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/ehr_agnostic_cot_mistral.json --logfile logs/ehr_agnostic_cot_mistral.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/ehr_agnostic_cot_llama2.json --logfile logs/ehr_agnostic_cot_llama2.log

:: EHR, MEDICAL, NOCOT
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/ehr_medical_nocot_llama3.json --logfile logs/ehr_medical_nocot_llama3.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/ehr_medical_nocot_llama3-gradient.json --logfile logs/ehr_medical_nocot_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/ehr_medical_nocot_nous-hermes2.json --logfile logs/ehr_medical_nocot_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/ehr_medical_nocot_gemma.json --logfile logs/ehr_medical_nocot_gemma.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/ehr_medical_nocot_mistral.json --logfile logs/ehr_medical_nocot_mistral.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/ehr_medical_nocot_llama2.json --logfile logs/ehr_medical_nocot_llama2.log

:: EHR, MEDICAL, COT
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama3 --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/ehr_medical_cot_llama3.json --logfile logs/ehr_medical_cot_llama3.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/ehr_medical_cot_nous-hermes2.json --logfile logs/ehr_medical_cot_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model gemma --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/ehr_medical_cot_gemma.json --logfile logs/ehr_medical_cot_gemma.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model mistral --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/ehr_medical_cot_mistral.json --logfile logs/ehr_medical_cot_mistral.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama2 --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/ehr_medical_cot_llama2.json --logfile logs/ehr_medical_cot_llama2.log

:::::::::::::: ISSC and ISSC-CoT ::::::::::::::::

:: TRUTHFULQA, AGNOSTIC, NOCOT
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model llama3 --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_nocot_llama3.json --logfile logs/truthfulqa_nocot_llama3.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model llama3-gradient --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_nocot_llama3-gradient.json --logfile logs/truthfulqa_nocot_llama3-gradient.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model nous-hermes2 --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_nocot_nous-hermes2.json --logfile logs/truthfulqa_nocot_nous-hermes2.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model gemma --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_nocot_gemma.json --logfile logs/truthfulqa_nocot_gemma.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model mistral --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_nocot_mistral.json --logfile logs/truthfulqa_nocot_mistral.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model llama2 --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_nocot_llama2.json --logfile logs/truthfulqa_nocot_llama2.log

:: TRUTHFULQA, AGNOSTIC, COT
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model llama3 --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_cot_llama3.json --logfile logs/truthfulqa_cot_llama3.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model nous-hermes2 --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_cot_nous-hermes2.json --logfile logs/truthfulqa_cot_nous-hermes2.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model gemma --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_cot_gemma.json --logfile logs/truthfulqa_cot_gemma.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model mistral --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_cot_mistral.json --logfile logs/truthfulqa_cot_mistral.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model llama2 --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_cot_llama2.json --logfile logs/truthfulqa_cot_llama2.log

:::::::::::::: SCA :::::::::::::::::

:: EHR, AGNOSTIC, COT
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama3 --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/ehr_agnostic_sca_llama3.json --logfile logs/ehr_agnostic_sca_llama3.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/ehr_agnostic_sca_nous-hermes2.json --logfile logs/ehr_agnostic_sca_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model gemma --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/ehr_agnostic_sca_gemma.json --logfile logs/ehr_agnostic_sca_gemma.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model mistral --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/ehr_agnostic_sca_mistral.json --logfile logs/ehr_agnostic_sca_mistral.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama2 --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/ehr_agnostic_sca_llama2.json --logfile logs/ehr_agnostic_sca_llama2.log

:: EHR, MEDICAL, COT
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama3 --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/ehr_medical_sca_llama3.json --logfile logs/ehr_medical_sca_llama3.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/ehr_medical_sca_nous-hermes2.json --logfile logs/ehr_medical_sca_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model gemma --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/ehr_medical_sca_gemma.json --logfile logs/ehr_medical_sca_gemma.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model mistral --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/ehr_medical_sca_mistral.json --logfile logs/ehr_medical_sca_mistral.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama2 --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/ehr_medical_sca_llama2.json --logfile logs/ehr_medical_sca_llama2.log

:: MEDQUAD, AGNOSTIC, COT
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/medquad_agnostic_sca_llama3.json --logfile logs/medquad_agnostic_sca_llama3.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/medquad_agnostic_sca_nous-hermes2.json --logfile logs/medquad_agnostic_sca_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/medquad_agnostic_sca_gemma.json --logfile logs/medquad_agnostic_sca_gemma.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/medquad_agnostic_sca_mistral.json --logfile logs/medquad_agnostic_sca_mistral.log

:: MEDQUAD, MEDICAL, COT
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3 --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/medquad_medical_sca_llama3.json --logfile logs/medquad_medical_sca_llama3.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model nous-hermes2 --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/medquad_medical_sca_nous-hermes2.json --logfile logs/medquad_medical_sca_nous-hermes2.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model gemma --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/medquad_medical_sca_gemma.json --logfile logs/medquad_medical_sca_gemma.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model mistral --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/medquad_medical_sca_mistral.json --logfile logs/medquad_medical_sca_mistral.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/medquad_medical_sca_llama2.json --logfile logs/medquad_medical_sca_llama2.log




:: VERY SLOW
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2 --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/medquad_agnostic_sca_llama2.json --logfile logs/medquad_agnostic_sca_llama2.log
::py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/medquad_agnostic_cot_llama3-gradient.json --logfile logs/medquad_agnostic_cot_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/ehr_agnostic_cot_llama3-gradient.json --logfile logs/ehr_agnostic_cot_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/ehr_medical_cot_llama3-gradient.json --logfile logs/ehr_medical_cot_llama3-gradient.log
::py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model llama3-gradient --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_cot_llama3-gradient.json --logfile logs/truthfulqa_cot_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/ehr_agnostic_sca_llama3-gradient.json --logfile logs/ehr_agnostic_sca_llama3-gradient.log
::py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/ehr_medical_sca_llama3-gradient.json --logfile logs/ehr_medical_sca_llama3-gradient.log
py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/medquad_agnostic_sca_llama3-gradient.json --logfile logs/medquad_agnostic_sca_llama3-gradient.log
py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama3-gradient --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/medquad_medical_sca_llama3-gradient.json --logfile logs/medquad_medical_sca_llama3-gradient.log

py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/medquad_medical_cot_llama2-13b.json --logfile logs/medquad_medical_cot_llama2-13b.log
py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/medquad_agnostic_cot_llama2-13b.json --logfile logs/medquad_agnostic_cot_llama2-13b.log
py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/medquad_medical_llama2-13b.json --logfile logs/medquad_medical_llama2-13b.log
py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/halueval_agnostic_nocot_llama2-13b.json --logfile logs/halueval_agnostic_nocot_llama2-13b.log
py -m detection.detect_hallucinations --data data/halueval_test.json --limit 100 --random --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/halueval_agnostic_cot_llama2-13b.json --logfile logs/halueval_agnostic_cot_llama2-13b.log
py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_nocot.prompt --outfile results/ehr_agnostic_nocot_llama2-13b.json --logfile logs/ehr_agnostic_nocot_llama2-13b.log
py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_agnostic_cot.prompt --outfile results/ehr_agnostic_cot_llama2-13b.json --logfile logs/ehr_agnostic_cot_llama2-13b.log
py -m detection.detect_hallucinations --data data/medical_report_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_medical_nocot.prompt --outfile results/ehr_medical_nocot_llama2-13b.json --logfile logs/ehr_medical_nocot_llama2-13b.log
py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama2:13b --times 5 --prompt prompts/detection/detect_context_block_q_medical_cot.prompt --outfile results/ehr_medical_cot_llama2-13b.json --logfile logs/ehr_medical_cot_llama2-13b.log
py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model llama2:13b --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_nocot_llama2-13b.json --logfile logs/truthfulqa_nocot_llama2-13b.log
py -m detection.contrast_samples --data data/truthfulqa_test_samples.json --limit 100 --model llama2:13b --prompt .\prompts\detection\detect_samples_sentences_noq_agnostic_cot.prompt --outfile results/truthful_qa_cot_llama2-13b.json --logfile logs/truthfulqa_cot_llama2-13b.log
py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama2:13b --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/ehr_agnostic_sca_llama2-13b.json --logfile logs/ehr_agnostic_sca_llama2-13b.log
py -m detection.detect_hallucinations --data data/medical_report_test.json --limit 100 --random --model llama2:13b --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/ehr_medical_sca_llama2-13b.json --logfile logs/ehr_medical_sca_llama2-13b.log
py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_sentences_q_agnostic_cot.prompt --outfile results/medquad_agnostic_sca_llama2-13b.json --logfile logs/medquad_agnostic_sca_llama2-13b.log
py -m detection.detect_hallucinations --data data/medquad_regen_test.json --model llama2:13b --times 5 --prompt prompts/detection/detect_context_sentences_q_medical_cot.prompt --outfile results/medquad_medical_sca_llama2-13b.json --logfile logs/medquad_medical_sca_llama2-13b.log
